### ISSUE TITLE
Python ImportError - No module named '_common'

### ISSUE THREAD

**Issue by pavitrakumar78** [opensim-org/opensim-core#1839]
Hi,

I have built and installed opensim with python bindings in Windows 10 with python 3.5. The build was successful and so were the tests.

```
PS E:\Software\opensim_stuff\opensim_build> ctest -C RelWithDebInfo --parallel 8
Test project E:/Software/opensim_stuff/opensim_build
      Start  1: testLepton
      Start  2: testC3DFileAdapter
      Start  3: testComponentInterface
      Start  4: testDataTable
      Start  5: testFunctionAdapter
      Start  6: testFunctions
      Start  7: testGCVSpline
      Start  8: testMarkerData
 1/90 Test  #1: testLepton ...................................   Passed    0.07 sec
 2/90 Test  #3: testComponentInterface .......................   Passed    0.20 sec
 3/90 Test  #7: testGCVSpline ................................   Passed    0.15 sec
 4/90 Test  #6: testFunctions ................................   Passed    0.16 sec
 5/90 Test  #5: testFunctionAdapter ..........................   Passed    0.17 sec
 6/90 Test  #4: testDataTable ................................   Passed    0.19 sec
 7/90 Test  #8: testMarkerData ...............................   Passed    0.16 sec
      Start  9: testNCSpline
      Start 10: testPath
      Start 11: testRootSolver
      Start 12: testSTOFileAdapter
      Start 13: testSerialization
      Start 14: testSmoothSegmentedFunctionFactory
      Start 15: testStorage
 8/90 Test #10: testPath .....................................   Passed    0.25 sec
 9/90 Test  #9: testNCSpline .................................   Passed    0.35 sec
10/90 Test #11: testRootSolver ...............................   Passed    0.34 sec
11/90 Test #13: testSerialization ............................   Passed    0.42 sec
12/90 Test #15: testStorage ..................................   Passed    0.41 sec
      Start 16: testTRCFileAdapter
      Start 17: testConstraints
      Start 18: testJoints
      Start 19: testAssemblySolver
      Start 20: testContactGeometry
13/90 Test  #2: testC3DFileAdapter ...........................   Passed    1.58 sec
14/90 Test #14: testSmoothSegmentedFunctionFactory ...........   Passed    1.31 sec
      Start 21: testForces
      Start 22: testFrames
15/90 Test #17: testConstraints ..............................   Passed    1.63 sec
16/90 Test #22: testFrames ...................................   Passed    0.54 sec
      Start 23: testInitState
      Start 24: testInverseKinematicsSolver
17/90 Test #18: testJoints ...................................   Passed    3.27 sec
18/90 Test #24: testInverseKinematicsSolver ..................   Passed    0.66 sec
      Start 25: testManager
      Start 26: testModelInterface
19/90 Test #21: testForces ...................................   Passed    2.26 sec
20/90 Test #25: testManager ..................................   Passed    0.76 sec
      Start 27: testMomentArms
      Start 28: testMuscleMetabolicsProbes
21/90 Test #26: testModelInterface ...........................   Passed    1.47 sec
      Start 29: testNestedModelComponents
22/90 Test #29: testNestedModelComponents ....................   Passed    0.90 sec
      Start 30: testPoints
23/90 Test #16: testTRCFileAdapter ...........................   Passed    7.47 sec
      Start 31: testPrescribedForce
24/90 Test #12: testSTOFileAdapter ...........................   Passed    9.42 sec
25/90 Test #30: testPoints ...................................   Passed    1.85 sec
26/90 Test #31: testPrescribedForce ..........................   Passed    0.59 sec
      Start 32: testProbes
      Start 33: testReportersWithModel
      Start 34: testStatesTrajectory
27/90 Test #33: testReportersWithModel .......................   Passed    0.61 sec
28/90 Test #28: testMuscleMetabolicsProbes ...................   Passed    4.93 sec
      Start 35: testActuators
      Start 36: testMuscleFirstOrderActivationDynamicModel
29/90 Test #36: testMuscleFirstOrderActivationDynamicModel ...   Passed    0.82 sec
      Start 37: testMuscleFixedWidthPennationModel
30/90 Test #35: testActuators ................................   Passed    1.50 sec
31/90 Test #37: testMuscleFixedWidthPennationModel ...........   Passed    0.67 sec
      Start 38: testMuscles
      Start 39: testSerializableMuscleCurves
32/90 Test #32: testProbes ...................................   Passed    2.61 sec
      Start 40: testControllers
33/90 Test #23: testInitState ................................   Passed   10.09 sec
34/90 Test #27: testMomentArms ...............................   Passed    7.93 sec
35/90 Test #39: testSerializableMuscleCurves .................   Passed    1.57 sec
      Start 41: testExternalLoads
      Start 42: testModelCopy
      Start 43: testSerializeOpenSimObjects
36/90 Test #41: testExternalLoads ............................   Passed    1.19 sec
37/90 Test #43: testSerializeOpenSimObjects ..................   Passed    1.08 sec
38/90 Test #38: testMuscles ..................................   Passed    3.01 sec
39/90 Test #42: testModelCopy ................................   Passed    1.47 sec
      Start 44: testVisualization
      Start 45: exampleHopperDevice
      Start 46: exampleHopperDeviceAnswers
      Start 47: testComponents
40/90 Test #44: testVisualization ............................   Passed    1.46 sec
      Start 48: testAddComponents
41/90 Test #45: exampleHopperDevice ..........................   Passed    3.49 sec
42/90 Test #40: testControllers ..............................   Passed    6.72 sec
      Start 49: testControllerExampleRuns
      Start 51: testExampleMainRuns
43/90 Test #49: testControllerExampleRuns ....................   Passed    1.49 sec
44/90 Test #46: exampleHopperDeviceAnswers ...................   Passed    6.23 sec
      Start 50: testControllerExample
      Start 53: testOptimizationExampleRuns
45/90 Test #20: testContactGeometry ..........................   Passed   23.82 sec
46/90 Test #50: testControllerExample ........................   Passed    1.70 sec
      Start 55: testCustomActuatorExampleRuns
      Start 57: testMuscleExampleRuns
47/90 Test #55: testCustomActuatorExampleRuns ................   Passed    1.52 sec
      Start 56: testCustomActuatorExample
48/90 Test #48: testAddComponents ............................   Passed    9.90 sec
49/90 Test #57: testMuscleExampleRuns ........................   Passed    3.50 sec
      Start 58: testMuscleExample
      Start 59: testSimpleOptimizationExampleRuns
50/90 Test #56: testCustomActuatorExample ....................   Passed    1.38 sec
51/90 Test #58: testMuscleExample ............................   Passed    0.60 sec
52/90 Test #51: testExampleMainRuns ..........................   Passed    8.79 sec
      Start 52: testExampleMain
      Start 61: testExampleModelRuns
      Start 62: testIterators
53/90 Test #59: testSimpleOptimizationExampleRuns ............   Passed    0.74 sec
54/90 Test #19: testAssemblySolver ...........................   Passed   29.27 sec
      Start 60: testSimpleOptimizationExample
      Start 63: testREADME
55/90 Test #52: testExampleMain ..............................   Passed    1.63 sec
56/90 Test #60: testSimpleOptimizationExample ................   Passed    0.71 sec
      Start 64: testWrapping
      Start 65: testExampleLuxoMuscle
57/90 Test #63: testREADME ...................................   Passed    1.01 sec
58/90 Test #62: testIterators ................................   Passed    2.50 sec
      Start 66: testAnalysisPluginExample
      Start 67: testBodyDragExample_Example1
59/90 Test #67: testBodyDragExample_Example1 .................   Passed    1.12 sec
60/90 Test #64: testWrapping .................................   Passed    3.57 sec
      Start 68: testBodyDragExample_Example2
      Start 69: testAnalyzeTool
61/90 Test #68: testBodyDragExample_Example2 .................   Passed    0.23 sec
62/90 Test #61: testExampleModelRuns .........................   Passed    7.46 sec
63/90 Test #66: testAnalysisPluginExample ....................   Passed    3.10 sec
      Start 70: testInducedAccelerations
      Start 71: testJointReactions
      Start 72: testStaticOptimization
64/90 Test #71: testJointReactions ...........................   Passed    1.59 sec
      Start 73: testForward
65/90 Test #34: testStatesTrajectory .........................   Passed   36.87 sec
      Start 74: testScale
66/90 Test #74: testScale ....................................   Passed   10.22 sec
      Start 75: testIK
67/90 Test #65: testExampleLuxoMuscle ........................   Passed   38.16 sec
      Start 76: testID
68/90 Test #75: testIK .......................................   Passed   13.86 sec
      Start 77: testCMCArm26_Millard
69/90 Test #76: testID .......................................   Passed    7.93 sec
      Start 78: testCMCArm26_Thelen
70/90 Test #73: testForward ..................................   Passed   66.46 sec
      Start 79: testCMCEMGDrivenArm_Millard
71/90 Test #69: testAnalyzeTool ..............................   Passed   76.25 sec
72/90 Test #70: testInducedAccelerations .....................   Passed   74.55 sec
      Start 80: testCMCEMGDrivenArm_Thelen
      Start 81: testCMCGait10dof18musc
73/90 Test #53: testOptimizationExampleRuns ..................   Passed   98.94 sec
      Start 54: testOptimizationExample
74/90 Test #78: testCMCArm26_Thelen ..........................   Passed   43.17 sec
      Start 82: testCMCSingleMuscle
75/90 Test #54: testOptimizationExample ......................   Passed    1.73 sec
      Start 83: testCMCSingleRigidTendonMuscle
76/90 Test #77: testCMCArm26_Millard .........................   Passed   52.50 sec
      Start 84: testCMCTwoMusclesOnBlock
77/90 Test #72: testStaticOptimization .......................   Passed  121.61 sec
      Start 85: testCMCWithControlConstraintsGait2354
78/90 Test #79: testCMCEMGDrivenArm_Millard ..................   Passed   51.66 sec
79/90 Test #80: testCMCEMGDrivenArm_Thelen ...................   Passed   46.82 sec
      Start 86: testCMCWithControlConstraintsRunningModel
      Start 87: testRRA
80/90 Test #83: testCMCSingleRigidTendonMuscle ...............   Passed   45.74 sec
81/90 Test #87: testRRA ......................................   Passed    9.93 sec
      Start 88: testCommandLineInterface
      Start 89: python_tests
82/90 Test #82: testCMCSingleMuscle ..........................   Passed   48.71 sec
      Start 90: python_examples
83/90 Test #90: python_examples ..............................   Passed    2.49 sec
84/90 Test #89: python_tests .................................   Passed   18.65 sec
85/90 Test #84: testCMCTwoMusclesOnBlock .....................   Passed   63.59 sec
86/90 Test #88: testCommandLineInterface .....................   Passed   29.45 sec
87/90 Test #85: testCMCWithControlConstraintsGait2354 ........   Passed  626.24 sec
88/90 Test #81: testCMCGait10dof18musc .......................   Passed  672.39 sec
89/90 Test #86: testCMCWithControlConstraintsRunningModel ....   Passed  624.30 sec
90/90 Test #47: testComponents ...............................   Passed  772.83 sec

100% tests passed, 0 tests failed out of 90

Total Test time (real) = 789.08 sec
```

I built opensim using the following commands:
```
git clone https://github.com/opensim-org/opensim-core.git
mkdir opensim_dependencies_build
cd .\opensim_dependencies_build
cmake ..\opensim-core\dependencies                             `
     -G"Visual Studio 14 2015 Win64"                          `
     -DCMAKE_INSTALL_PREFIX="..\opensim_dependencies_install"
cmake --build . --config RelWithDebInfo -- /maxcpucount:4
cd ..
mkdir opensim_build
cd .\opensim_build
cmake ..\opensim-core                                              `
     -G"Visual Studio 14 2015 Win64"                              `
     -DCMAKE_INSTALL_PREFIX="..\opensim_install"                  `
     -DOPENSIM_DEPENDENCIES_DIR="..\opensim_dependencies_install" `
     -DBUILD_JAVA_WRAPPING=OFF                                     `
     -DBUILD_PYTHON_WRAPPING=ON                                   `
     -DWITH_BTK=ON
     -DOPENSIM_PYTHON_VERSION=3
     -DSWIG_EXECUTABLE="E:\Software\swigwin-3.0.12\swig.exe"
cmake --build . --config RelWithDebInfo -- /maxcpucount:4
ctest -C RelWithDebInfo --parallel 8
```

But when I try
`import opensim` in python, I get the following error:

```
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensim
Traceback (most recent call last):
  File "E:\Software\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\opensim-4.0-py3.5.egg\opensim\common.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "E:\Software\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Software\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\opensim-4.0-py3.5.egg\opensim\__init__.py", line 2, in <module>
    from .common import *
  File "E:\Software\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\opensim-4.0-py3.5.egg\opensim\common.py", line 17, in <module>
    _common = swig_import_helper()
  File "E:\Software\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\site-packages\opensim-4.0-py3.5.egg\opensim\common.py", line 16, in swig_import_helper
    return importlib.import_module('_common')
  File "E:\Software\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_common'
```
Should I add any dir to `PATH` in windows?

**Comment by chrisdembia** [comment]
Yes; add `<...>/opensim-core/bin` to your PATH.

**Comment by pavitrakumar78** [comment]
@chrisdembia There is no folder named `bin` in the opensim-core folder. The only `bin` folders I see are in BTK, docopt and simbody.

**Comment by chrisdembia** [comment]
Oops; sorry, I mean in `opensim_install`

**Comment by pavitrakumar78** [comment]
@chrisdembia Hmm ... weird... `opensim_install` has only 1 folder called `sdk`. So its `opensim_install>sdk>python>opensim>simbody` and nothing else. Did I build it incorrectly?..

**Comment by chrisdembia** [comment]
Did you run `cmake --build . --config RelWithDebInfo --target install -- /maxcpucount:4`?

**Comment by pavitrakumar78** [comment]
I ran the "Windows-Impatient-Method" (https://github.com/opensim-org/opensim-core#for-the-impatient-windows)

So, the steps I followed (same as my original post) are:

```
git clone https://github.com/opensim-org/opensim-core.git
mkdir opensim_dependencies_build
cd .\opensim_dependencies_build
cmake ..\opensim-core\dependencies                             `
     -G"Visual Studio 14 2015 Win64"                          `
     -DCMAKE_INSTALL_PREFIX="..\opensim_dependencies_install"
cmake --build . --config RelWithDebInfo -- /maxcpucount:4
cd ..
mkdir opensim_build
cd .\opensim_build
cmake ..\opensim-core                                              `
     -G"Visual Studio 14 2015 Win64"                              `
     -DCMAKE_INSTALL_PREFIX="..\opensim_install"                  `
     -DOPENSIM_DEPENDENCIES_DIR="..\opensim_dependencies_install" `
     -DBUILD_JAVA_WRAPPING=OFF                                     `
     -DBUILD_PYTHON_WRAPPING=ON                                   `
     -DWITH_BTK=ON
     -DOPENSIM_PYTHON_VERSION=3
     -DSWIG_EXECUTABLE="E:\Software\swigwin-3.0.12\swig.exe"
cmake --build . --config RelWithDebInfo -- /maxcpucount:4
ctest -C RelWithDebInfo --parallel 8
```
So, should I remove contents of the opensim_install dir and rerun the following?

```
cd .\opensim_build
cmake ..\opensim-core                                              `
     -G"Visual Studio 14 2015 Win64"                              `
     -DCMAKE_INSTALL_PREFIX="..\opensim_install"                  `
     -DOPENSIM_DEPENDENCIES_DIR="..\opensim_dependencies_install" `
     -DBUILD_JAVA_WRAPPING=OFF                                     `
     -DBUILD_PYTHON_WRAPPING=ON                                   `
     -DWITH_BTK=ON
     -DOPENSIM_PYTHON_VERSION=3
     -DSWIG_EXECUTABLE="E:\Software\swigwin-3.0.12\swig.exe"
cmake --build . --config RelWithDebInfo --target install -- /maxcpucount:4
ctest -C RelWithDebInfo --parallel 8
```

**Comment by chrisdembia** [comment]
No, just run the command I specified (from `opensim_build`).

**Comment by pavitrakumar78** [comment]
@chrisdembia Yep! got it! I can now import opensim in python! Thank you!

**Comment by chrisdembia** [comment]
@pavitrakumar78 thanks for using OpenSim! would you consider submitting a PR to update the README so that others can avoid the issue you had?

**Comment by pavitrakumar78** [comment]
@chrisdembia Sure! I have modified the `README.md` file - added the command you suggested to the impatient method for windows. Please review PR #1840 when you can.
Just to sum up, the commands that I used to build opensim on my environment are:
```
git clone https://github.com/opensim-org/opensim-core.git
mkdir opensim_dependencies_build
cd .\opensim_dependencies_build
cmake ..\opensim-core\dependencies                             `
     -G"Visual Studio 14 2015 Win64"                          `
     -DCMAKE_INSTALL_PREFIX="..\opensim_dependencies_install"
cmake --build . --config RelWithDebInfo -- /maxcpucount:4
cd ..
mkdir opensim_build
cd .\opensim_build
cmake ..\opensim-core                                              `
     -G"Visual Studio 14 2015 Win64"                              `
     -DCMAKE_INSTALL_PREFIX="..\opensim_install"                  `
     -DOPENSIM_DEPENDENCIES_DIR="..\opensim_dependencies_install" `
     -DBUILD_JAVA_WRAPPING=OFF                                     `
     -DBUILD_PYTHON_WRAPPING=ON                                   `
     -DWITH_BTK=ON
     -DOPENSIM_PYTHON_VERSION=3
     -DSWIG_EXECUTABLE="E:\Software\swigwin-3.0.12\swig.exe"
cmake --build . --config RelWithDebInfo -- /maxcpucount:4
cmake --build . --config RelWithDebInfo --target install -- /maxcpucount:4
ctest -C RelWithDebInfo --parallel 8
```
My environment:
Windows 10
Python 3.5
Visual Studio 2015 (Update 3)
(I do not use Anaconda; I do not need Java bindings - so no MATLAB)
Also, I think it would be better if there was a command to specify which python should opensim be build on. Something similar to `-DSWIG_EXECUTABLE` . I had a problem with this and had to remove a old python source to force CMake to detect a newer python source installed on my computer.

**Comment by chrisdembia** [comment]
>  I had a problem with this and had to remove a old python source to force CMake to detect a newer python source installed in a differerent path.

We have tried to support this, using the `OPENSIM_PYTHON_VERSION` CMake variable. However, if you change this variable after running the first time, you likely have to delete your CMake cache file (CMakeCache.txt in the build dir).

**Comment by pavitrakumar78** [comment]
I do not mean the `OPENSIM_PYTHON_VERSION` variable. For example, consider the scenario I had:
I have installed python 3.5 in my `E` drive which is the python that I use globally (i.e It's path is in `PATH` and `PYTHONPATH` env. vars). But, I also have cywgin installed in another drive `C`. Now I need to add `cygwin/bin` to PATH also. But tha that `bin` folder contains cygwin's python installation. So, trying out `where python` in windows gives me 2 paths (one cygwin, one actual python dir that I use). Even after mentioning `OPENSIM_PYTHON_VERSION=3`, CMake kept choosing the cygwin's python installation and gave me an incorrect python version error. So, I had to temporarily delete python sources from cygwin's `bin` folder and re-execute CMake after deleting pre-build cache so that CMake uses the python 3.5 dir instead.
So, what I thought was, if there was a variable like `CMAKE_PYTHON_PATH` or something like that - you can avoid these errors. However, it might not be required because my problem might be very specific and many users will probably not face it.

**Comment by chrisdembia** [comment]
Sorry for misunderstanding.

You must set all the `PYTHON_` variables yourself (e.g., `PYTHON_INCLUDE_DIR`, `PYTHON_LIBRARY`, `PYTHON_EXECUTABLE`). This is probably easier using the CMake GUI.

**Comment by pavitrakumar78** [comment]
> Sorry for misunderstanding.
> 
> You must set all the PYTHON_ variables yourself (e.g., PYTHON_INCLUDE_DIR, PYTHON_LIBRARY, PYTHON_EXECUTABLE). This is probably easier using the CMake GUI.

Got it! Thanks for the info!
