### ISSUE TITLE
Old model file does not open in 4.0, but opens in 3.3 and opens after converting/saving in 3.3

### ISSUE THREAD

**Issue by tkuchida** [opensim-org/opensim-core#2050]
@tkuchida commented on [Thu Jan 11 2018](https://github.com/opensim-org/opensim-gui/issues/470)

One of Sam's model files (version 10600) does not open in 4.0. Messages window:
<pre>
Updating Model file from 10600 to latest format...
Model name '3D Gait Model with Simple Arms' contains whitespace. It was renamed '3DGaitModelwithSimpleArms'.
Got 0 object values for Property function but the minimum is 1. Continuing anyway.
Got 0 object values for Property function but the minimum is 1. Continuing anyway.
[35 more instances of the same error.]
Loaded model 3DGaitModelwithSimpleArms from file [path]\FullBodyModel_SimpleArms_Hamner2010_HPLMarkers_subject05_v191.osim
</pre>
Nothing appears in the visualizer window despite the Messages window reporting that the model was loaded. The Navigator panel is also empty. Red-circle error message:
<pre>
java.lang.RuntimeException: SimTK Exception thrown at TransformAxis.cpp:89:
  Internal bug detected: CustomJoint (ground_pelvis) r1 axis has no function but has coordinates.
  (Assertion 'coordNames.size() == 0' failed).
  Please file an Issue at https://github.com/simbody/simbody/issues.
  Include the above information and anything else needed to reproduce the problem.
	at org.opensim.modeling.opensimSimulationJNI.Model_initSystem(Native Method)
	at org.opensim.modeling.Model.initSystem(Model.java:840)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:146)
	at org.opensim.view.pub.OpenSimDB.addModel(OpenSimDB.java:141)
	at org.opensim.view.FileOpenOsimModelAction$2.run(FileOpenOsimModelAction.java:98)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
</pre>
The model opens in 3.3 and, once saved in 3.3, can be opened in 4.0. Seems like 4.0 should be able to do whatever 3.3 is doing. If not possible, then a dialog box (or the Messages window) should tell the user to open/re-save in 3.3 if that's the suggested resolution.

**Comment by aseth1** [comment]
@tkuchida thanks for finding this. Please post the model. (I have Sam's SimTK download but I only see pre 1.6 (no version number) or 20001 models.) Thanks!

**Comment by tkuchida** [comment]
Thanks for investigating. Here's the [link](https://drive.google.com/file/d/1Ut1u0IP_1qIXg6lrYIY05ocgwT0vrdCT/view?usp=sharing). Related: #206.
