### ISSUE TITLE
Scaled Hamner model can't be opened. 

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2151]
From Sam's SimTK package; The base models opens, but the scaled models (distributed in the download) throws an exception.

[FullBodyModel_Hamner2010_v2_0 - Copy.osim.txt](https://github.com/opensim-org/opensim-core/files/1904225/FullBodyModel_Hamner2010_v2_0.-.Copy.osim.txt)

[subject02_scaled_v2_0.osim.txt](https://github.com/opensim-org/opensim-core/files/1904226/subject02_scaled_v2_0.osim.txt)

```
java.lang.RuntimeException: SimTK Exception thrown at Xml.cpp:820:
  Error detected by Simbody method Xml::Element::getAs(): The given Node was not an Element; it is a NoNode. Use Element::isA() to check before calling Element::getAs().
  (Required condition 'isA(node)' was not met.)

	at org.opensim.modeling.opensimSimulationJNI.new_Model__SWIG_1(Native Method)
	at org.opensim.modeling.Model.<init>(Model.java:783)
	at org.opensim.view.FileOpenOsimModelAction.loadModel(FileOpenOsimModelAction.java:123)
	at org.opensim.view.FileOpenOsimModelAction.loadModel(FileOpenOsimModelAction.java:117)
	at org.opensim.view.FileOpenOsimModelAction$1.run(FileOpenOsimModelAction.java:59)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

![hamner_exception](https://user-images.githubusercontent.com/5296507/38692076-42d8de02-3e72-11e8-80fa-994401143d24.png)

**Comment by jimmyDunne** [comment]
@jenhicks and I did discuss adding a new download to Sam's project that works in 4.0. I would need to write a note on the SimTK page about the changes and that users shouldn't expect the exact answers compared to Sam's original paper. 

This may apply to other popular projects— the [Liu (2008)](https://simtk.org/projects/mspeedwalksims) project still gets used a lot and the models from there would also have to go through multiple intermediates.

**Comment by aseth1** [comment]
Updating these projects (Liu, Hamner, Steele, Arnold, ...) and regenerating results will be a lot of work on our part. I think it is OK that these projects require specific versions of OpenSim for reproduction purposes. It would be great if we had community members add updated downloads of models and results after upgrading OpenSim and regenerating results themselves.

**Comment by jenhicks** [comment]
Closing as this is duplicated elsewhere.
