### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__simbody), install for terminal in python 3.6 and ubuntu 18.04

### ISSUE THREAD

**Issue by damvantai** [opensim-org/opensim-core#2392]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/opensim-4.1-py3.6.egg/opensim/__init__.py", line 1, in <module>
    from .simbody import *
  File "/usr/local/lib/python3.6/dist-packages/opensim-4.1-py3.6.egg/opensim/simbody.py", line 17, in <module>
    _simbody = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/opensim-4.1-py3.6.egg/opensim/simbody.py", line 16, in swig_import_helper
    return importlib.import_module('_simbody')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dynamic module does not define module export function (PyInit__simbody)

**Comment by damvantai** [comment]
build with python3 add -DOPENSIM_PYTHON_VERSION=3 to cmake
