### ISSUE TITLE
InverseKinematicsStudy, setModel(), & set_model_file_name()

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2455]
(Matlab, Mac)

`InverseKinematicsStudy` method `setModel()` would be useful since `OpenSimUtilities.calibrateModelFromOrientations()` returns a calibrated model. A user wouldn't have to write a calibrated model to file as an intermediate step. 

However, if I give setModel() a model, but don't have any value for set_model_file_name(), i get an exception

```
>> ik.setModel(obj.calibratedModel)
>> ik.set_model_file_name('')
>> ik.run()
Java exception occurred:
java.lang.RuntimeException: Object: Cannot construct from empty filename. No filename specified.
	Thrown at Object.cpp:100 in Object().
	at org.opensim.modeling.opensimSimulationJNI.InverseKinematicsStudy_run__SWIG_1(Native Method)
	at org.opensim.modeling.InverseKinematicsStudy.run(InverseKinematicsStudy.java:381)
```

It would be great if a user could use either a Model or a ModelPath.

**Comment by jimmyDunne** [comment]
I think that this is possibly a more general issue than with OpenSense since the other tools have similar issues. Perhaps down the road we can look at the interface and see how it could be more flexible across scripting and command line functions. For now, I will ignore the setModel() method and just use intermediate models files.
