### ISSUE TITLE
Exception for calibrateModelFromOrientations() in python

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2481]
When running calibrateModelFromOrientations() in python, an exception is returned;

``` python
 model = ou.calibrateModelFromOrientations(modelFileName,orientationsFileName,baseIMUName,'z',1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "opensim/simulation.py", line 71990, in calibrateModelFromOrientations
    return _simulation.OpenSenseUtilities_calibrateModelFromOrientations(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'OpenSenseUtilities_calibrateModelFromOrientations'.
  Possible C/C++ prototypes are:
    OpenSim::OpenSenseUtilities::calibrateModelFromOrientations(std::string const &,std::string const &,std::string const &,SimTK::CoordinateAxis const &,bool)
    OpenSim::OpenSenseUtilities::calibrateModelFromOrientations(std::string const &,std::string const &,std::string const &,SimTK::CoordinateAxis const &)
    OpenSim::OpenSenseUtilities::calibrateModelFromOrientations(std::string const &,std::string const &,std::string const &)
    OpenSim::OpenSenseUtilities::calibrateModelFromOrientations(std::string const &,std::string const &)
```

It seems to have to do with the Coordinate Axis. If I run the function without the coordinate axis it performs fine. 

```
 model = ou.calibrateModelFromOrientations(modelFileName,orientationsFileName,baseIMUName)
```

**Comment by aymanhab** [comment]
Can you use CoordinateAxis(i) on the call line (i=0 or 1 or 2)? I'm building now to test that.
