### ISSUE TITLE
Exception for InverseKinematicsStudy.run() in python

### ISSUE THREAD

**Issue by jimmyDunne** [opensim-org/opensim-core#2482]
When performing InverseKinematicsStudy.run(bool) an exception is returned 

``` python 

# Instantiate an InverseKinematicsStudy
ik = osim.InverseKinematicsStudy();
...

# Run IK
ik.run(1);
Traceback (most recent call last):
  File "OpenSense_OrientationTracking.py", line 64, in <module>
    ik.run(1);
  File "/Users/jimmy/Applications/OpenSense/sdk/Python/opensim/simulation.py", line 73032, in run
    return _simulation.InverseKinematicsStudy_run(self, visualizeResults)
NotImplementedError: Wrong number or type of arguments for overloaded function 'InverseKinematicsStudy_run'.
  Possible C/C++ prototypes are:
    OpenSim::InverseKinematicsStudy::run(bool)
    OpenSim::InverseKinematicsStudy::run()
```

However, when the method is executed without the input bool, it runs without issue. 

```
ik.run()
Loaded model imuTrackingModel from file calibrated_imuTrackingModel.osim
Loading orientations as quaternions from MT_012005D6_009-001_orientations.sto
Heading correction for base 'pelvis_imu' along its 'z' axis.
Heading correction computed to be 139.134degs about ground Y
Solved frame at time: 7.25
Solved frame at time: 7.26
Solved frame at time: 7.27
Solved frame at time: 7.28
Solved frame at time: 7.29
Solved frame at time: 7.3
Solved frame at time: 7.31
Solved frame at time: 7.32
...
```

**Comment by aymanhab** [comment]
You can pass True as an argument and it visualizes.
