### ISSUE TITLE
Segmentation fault on example from Sandbox (futureOrientationInverseKinematics)

### ISSUE THREAD

**Issue by yurket** [opensim-org/opensim-core#2494]
I've got a segfault when running an example `futureOrientationInverseKinematics.cpp` from a Sandbox folder. Opensim is built from master with a "superbuild" method, so all dependencies should have the same CMAKE_BUILD_TYPE.

Here's the output from the run:
```
user @ localhost ~/build/my_opensim_tests/build $ ./myexe 
Updating Model file from 30000 to latest format...
Model name '3D Upper Limb Model' contains whitespace. It was renamed '3DUpperLimbModel'.
Loaded model 3DUpperLimbModel from file futureOrientationInverseKinematics.osim
Couldn't find file 'hat_spine.vtp'.
Couldn't find file 'hat_jaw.vtp'.
Couldn't find file 'hat_skull.vtp'.
Couldn't find file 'hat_ribs_scap.vtp'.
...
Couldn't find file 'thumb_proximal_lvs.vtp'.
Couldn't find file 'thumb_distal_lvs.vtp'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathwrap'.
The duplicate is being renamed to 'pathwrap_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathwrap'.
The duplicate is being renamed to 'pathwrap_0'.
GeometryPath 'geometrypath' has subcomponents with duplicate name 'pathwrap'.
The duplicate is being renamed to 'pathwrap_1'.
Loaded marker file futureOrientationInverseKinematics.trc (2 markers, 1202 frames)
Segmentation fault (core dumped)
```

And here's a stacktrace from gdb:
```
>>> bt
#0  0x0000555555597a8f in SimTK::ListOfDependents::notePrerequisiteChange(SimTK::StateImpl const&) const ()
#1  0x0000555555596fbf in SimTK::CacheEntryInfo::invalidate(SimTK::StateImpl const&) ()
#2  0x0000555555597ac0 in SimTK::ListOfDependents::notePrerequisiteChange(SimTK::StateImpl const&) const ()
#3  0x00007ffff5532046 in SimTK::StateImpl::noteUChange (this=0x555555901220) at /home/lite/build/opensim-core/dependencies/simbody/SimTKcommon/Simulation/include/SimTKcommon/internal/StateImpl.h:2142
#4  SimTK::StateImpl::noteYChange (this=0x555555901220) at /home/lite/build/opensim-core/dependencies/simbody/SimTKcommon/Simulation/include/SimTKcommon/internal/StateImpl.h:2146
#5  SimTK::StateImpl::invalidateJustSystemStage (this=this@entry=0x555555901220, stg=stg@entry=...) at /home/lite/build/opensim-core/dependencies/simbody/SimTKcommon/Simulation/src/State.cpp:504
#6  0x00007ffff620954b in SimTK::StateImpl::invalidateAll (g=..., this=0x555555901220) at /home/lite/build/opensim-core/dependencies/simbody/SimTKcommon/Simulation/include/SimTKcommon/internal/StateImpl.h:1032
#7  SimTK::StateImpl::updDiscreteVariable (dk=..., this=0x555555901220) at /home/lite/build/opensim-core/dependencies/simbody/SimTKcommon/Simulation/include/SimTKcommon/internal/StateImpl.h:1974
#8  SimTK::State::updDiscreteVariable (index=..., subsys=..., this=this@entry=0x7fffffffdaa8) at /home/lite/build/opensim-core/dependencies/simbody/SimTKcommon/Simulation/include/SimTKcommon/internal/StateImpl.h:2447
#9  SimbodyMatterSubsystemRep::updModelVars (s=..., this=<optimized out>) at /home/lite/build/opensim-core/dependencies/simbody/Simbody/src/SimbodyMatterSubsystemRep.h:1149
#10 SimbodyMatterSubsystemRep::setUseEulerAngles (this=<optimized out>, s=..., useAngles=<optimized out>) at /home/lite/build/opensim-core/dependencies/simbody/Simbody/src/SimbodyMatterSubsystemRep.cpp:1760
#11 0x00007ffff61fc594 in SimTK::SimbodyMatterSubsystem::setUseEulerAngles (this=<optimized out>, s=..., useAngles=useAngles@entry=true) at /home/lite/build/opensim-core/dependencies/simbody/Simbody/src/SimbodyMatterSubsystem.cpp:1961
#12 0x00007ffff6e68639 in OpenSim::Model::initializeState() () at /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/g++-v8/bits/unique_ptr.h:342
#13 0x0000555555598dec in OpenSim::Model::initSystem() ()
#14 0x000055555559b5d9 in OrientationIK::run() ()
#15 0x000055555558ef24 in main ()
```

My environment:
```
user @ localhost ~/build/my_opensim_tests/build $ emerge --info
Portage 2.3.66 (python 3.6.8-final-0, default/linux/amd64/17.0/systemd, gcc-8.2.0, glibc-2.29-r2, 4.19.27-gentoo-r1 x86_64)
=================================================================
System uname: Linux-4.19.27-gentoo-r1-x86_64-AMD_Ryzen_7_2700X_Eight-Core_Processor-with-gentoo-2.6
KiB Mem:    32948404 total,  19131448 free
KiB Swap:          0 total,         0 free
Timestamp of repository gentoo: Fri, 14 Jun 2019 19:30:01 +0000
Head commit of repository gentoo: 0d4039191a3b7a32c45ed7a85296276f65a707a2
sh bash 4.4_p23-r1
ld GNU ld (Gentoo 2.30 p5) 2.30.0
app-shells/bash:          4.4_p23-r1::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.28.2-r1::gentoo
dev-lang/python:          2.7.15::gentoo, 3.6.8::gentoo, 3.7.3::gentoo
dev-util/cmake:           3.14.3::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6-r1::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.13-r1::gentoo, 2.69-r4::gentoo
sys-devel/automake:       1.11.6-r3::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.30-r4::gentoo, 2.31.1-r6::gentoo
sys-devel/gcc:            6.4.0-r1::gentoo, 7.3.0-r3::gentoo, 8.2.0-r6::gentoo, 8.3.0-r1::gentoo
sys-devel/gcc-config:     2.0::gentoo
sys-devel/libtool:        2.4.6-r3::gentoo
sys-devel/make:           4.2.1-r4::gentoo
sys-kernel/linux-headers: 4.14-r1::gentoo (virtual/os-headers)
sys-libs/glibc:           2.29-r2::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-metamanifest: yes
    sync-rsync-extra-opts: 
    sync-rsync-verify-jobs: 1

ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=znver1 -O2 -pipe"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-march=znver1 -O2 -pipe"
DISTDIR="/mnt/old_storage/usr/portage/distfiles"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=znver1 -O2 -pipe"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-march=znver1 -O2 -pipe"
GENTOO_MIRRORS="https://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/ http://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/ ftp://ftp-stud.hs-esslingen.de/pub/Mirrors/gentoo/ rsync://ftp-stud.hs-esslingen.de/gentoo/ https://mirror.yandex.ru/gentoo-distfiles/ http://mirror.yandex.ru/gentoo-distfiles/ ftp://mirror.yandex.ru/gentoo-distfiles/"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j15"
PKGDIR="/usr/portage/packages"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/tmp"
USE="X acl acpi alsa amd64 bash-completion berkdb bindist btrfs bzip2 cli crypt cxx dbus djvu dri fortran gdbm git gtk gzip hdf5 iconv inotify ipv6 jack jpeg libnotify libtirpc lm_sensors mp3 mp4 multilib ncurses nls nptl ntfs openmp pam pcre pdf png profile pulseaudio python readline seccomp sound ssl systemd tcpd udev unicode upnp upower usb wifi xattr zip zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="libinput" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" NETBEANS_MODULES="apisupport cnd groovy gsf harness ide identity j2ee java mobility nb php profiler soa visualweb webcommon websvccommon xml" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-2" POSTGRES_TARGETS="postgres10 postgres11" PYTHON_SINGLE_TARGET="python3_6" PYTHON_TARGETS="python2_7 python3_6" RUBY_TARGETS="ruby24" USERLAND="GNU" VIDEO_CARDS="nvidia" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, LINGUAS, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
```

**Comment by jimmyDunne** [comment]
The Sandbox folder is for experimental scripts and documents for the development team. We don't offer support to any of the experimental scripts or classes in that folder. 

If you are interested in Orientation tracking with OpenSim there is information and an example [here](https://simtk-confluence.stanford.edu:8443/display/OpenSim/OpenSense+-+Kinematics+with+IMU+Data).
