### ISSUE TITLE
Import Opensim in Python on Linux

### ISSUE THREAD

**Issue by aclouthier** [opensim-org/opensim-core#2966]
I'm having trouble importing opensim in python on Ubuntu 18.04. 
All of the tests passed after installation, except the two python tests. 
I have set the following variables:
export PATH=/data/opensim/opensim_install/bin:$PATH
export LD_LIBRARY_PATH=/data/opensim/opensim_install/lib

and ran setup.py, but it seems to not be finding some libraries. When I try to import opensim in python, I get the following error:

```
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensim
Traceback (most recent call last):
  File "/data/opensim/opensim_install/lib/python3.6/site-packages/opensim/moco.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libadolc.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/opensim/opensim_install/lib/python3.6/site-packages/opensim/__init__.py", line 8, in <module>
    from .moco import *
  File "/data/opensim/opensim_install/lib/python3.6/site-packages/opensim/moco.py", line 17, in <module>
    _moco = swig_import_helper()
  File "/data/opensim/opensim_install/lib/python3.6/site-packages/opensim/moco.py", line 16, in swig_import_helper
    return importlib.import_module('_moco')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_moco'
```

Does anyone have any ideas what the issue might be?

**Comment by aclouthier** [comment]
I resolved this error by copying the adolc and ipopt library files from opensim_build_install to opensim_install/lib.
I was then getting an error that OpenSim had no module 'common', but this seems to have somehow resolved itself and is now working.

**Comment by Kartik-Sama** [comment]
@aclouthier, I have been facing the same issue, i.e. the 2 tests related to python failing. However upon importing opensim the module itself is not found in my case. Could please share the versions of g++, swig, doxygen and python that you have used to compile the binaries on Ubuntu 18.04? Thanks in advance.

**Comment by aclouthier** [comment]
Sure, I'm not sure how to find the doxygen version, but here are the others:
python 3.6.9
g++ 7.5.0
swig 3.0.12
