### ISSUE TITLE
Python API error on Linux

### ISSUE THREAD

**Issue by bretthannigan** [opensim-org/opensim-core#2993]
Hi, 

I am compiling Opensim 4.1 by following the [steps ](https://simtk-confluence.stanford.edu/display/OpenSim/Linux+Support) and all seems to compile correctly. All ctest tests pass except python_tests and python_examples. I am using Python 3.7.6. When I follow the [instructions ](https://simtk-confluence.stanford.edu/display/OpenSim/Scripting+in+Python#ScriptinginPython-Ubuntu) for installing the Python API, the line `import opensim` works correctly in the <OPENSIM_INSTALL_DIR>/lib/python3.7/site-packages directory. If I then try the same line in a Python interpreter in any other directory, I get the error:
```
Python 3.7.6 (default, Feb 24 2021, 11:51:57)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/localhome/bchannig/.local/lib/python3.7/site-packages/opensim-4.1-py3.7.egg/opensim/__init__.py", line 1, in <module>
  File "/localhome/bchannig/.local/lib/python3.7/site-packages/opensim-4.1-py3.7.egg/opensim/simbody.py", line 13, in <module>
ImportError: cannot import name '_simbody' from 'opensim' (/localhome/bchannig/.local/lib/python3.7/site-packages/opensim-4.1-py3.7.egg/opensim/__init__.py)```
Any advice on how to fix this?

**Comment by bretthannigan** [comment]
Issue fixed by downgrading to Swig 3.0.8 and following these instructions: https://github.com/opensim-org/opensim-core/issues/2664#issue-550711523
