### ISSUE TITLE
from . import _simbody DLL load failed in OpenSim 4.3 Python API

### ISSUE THREAD

**Issue by hwy1992129** [opensim-org/opensim-core#3103]
My OS is Windows 10, the python version is 3.7
I installed the binary OpenSim 4.3 and I want to install the API to my environment. However, it fails when opensim is imported....
I am moving to OpenSim 4.3 API, because the old version doesn't have "to_numpy()" and I believe the numpy array conversion should be helpful...
I think the environment path should be correct..... I modify the path based on the previous 4.1 version.. The 4.1 API is working well. I also test... The 4.1 API can be installed in Blender, Blender also works well with 4.1. I have two OpenSim right now, and they are not in the same drive.
I got the same error when I switched into 4.3.
![image](https://user-images.githubusercontent.com/70329303/140701126-3c18027a-860b-404e-b784-229f7e0fc4dd.png)
![image](https://user-images.githubusercontent.com/70329303/140701088-73270652-e79c-4f48-af0b-87c969a6ba2f.png)
![image](https://user-images.githubusercontent.com/70329303/140701183-de6e193c-8b58-4c7c-8bf9-42675242486a.png)

The error is should below.
```
(opensim43) PS C:\OpenSim 4.3\sdk\Python> python setup.py install
running install
running bdist_egg
running egg_info
creating opensim.egg-info
writing opensim.egg-info\PKG-INFO
writing dependency_links to opensim.egg-info\dependency_links.txt
writing entry points to opensim.egg-info\entry_points.txt
writing top-level names to opensim.egg-info\top_level.txt
writing manifest file 'opensim.egg-info\SOURCES.txt'
reading manifest file 'opensim.egg-info\SOURCES.txt'
writing manifest file 'opensim.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\opensim
copying opensim\actuators.py -> build\lib\opensim
copying opensim\analyses.py -> build\lib\opensim
copying opensim\common.py -> build\lib\opensim
copying opensim\examplecomponents.py -> build\lib\opensim
copying opensim\moco.py -> build\lib\opensim
copying opensim\report.py -> build\lib\opensim
copying opensim\simbody.py -> build\lib\opensim
copying opensim\simulation.py -> build\lib\opensim
copying opensim\tools.py -> build\lib\opensim
copying opensim\version.py -> build\lib\opensim
copying opensim\__init__.py -> build\lib\opensim
copying opensim\_actuators.lib -> build\lib\opensim
copying opensim\_actuators.pyd -> build\lib\opensim
copying opensim\_analyses.lib -> build\lib\opensim
copying opensim\_analyses.pyd -> build\lib\opensim
copying opensim\_common.lib -> build\lib\opensim
copying opensim\_common.pyd -> build\lib\opensim
copying opensim\_examplecomponents.lib -> build\lib\opensim
copying opensim\_examplecomponents.pyd -> build\lib\opensim
copying opensim\_moco.lib -> build\lib\opensim
copying opensim\_moco.pyd -> build\lib\opensim
copying opensim\_simbody.lib -> build\lib\opensim
copying opensim\_simbody.pyd -> build\lib\opensim
copying opensim\_simulation.lib -> build\lib\opensim
copying opensim\_simulation.pyd -> build\lib\opensim
copying opensim\_tools.lib -> build\lib\opensim
copying opensim\_tools.pyd -> build\lib\opensim
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\actuators.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\analyses.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\common.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\examplecomponents.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\moco.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\report.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\simbody.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\simulation.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\tools.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\version.py -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_actuators.lib -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_actuators.pyd -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_analyses.lib -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_analyses.pyd -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_common.lib -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_common.pyd -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_examplecomponents.lib -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_examplecomponents.pyd -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_moco.lib -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_moco.pyd -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_simbody.lib -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_simbody.pyd -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_simulation.lib -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_simulation.pyd -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_tools.lib -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\_tools.pyd -> build\bdist.win-amd64\egg\opensim
copying build\lib\opensim\__init__.py -> build\bdist.win-amd64\egg\opensim
byte-compiling build\bdist.win-amd64\egg\opensim\actuators.py to actuators.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\analyses.py to analyses.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\common.py to common.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\examplecomponents.py to examplecomponents.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\moco.py to moco.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\report.py to report.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\simbody.py to simbody.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\simulation.py to simulation.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\tools.py to tools.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\version.py to version.cpython-37.pyc
byte-compiling build\bdist.win-amd64\egg\opensim\__init__.py to __init__.cpython-37.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying opensim.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying opensim.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying opensim.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying opensim.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying opensim.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\opensim-4.3-py3.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing opensim-4.3-py3.7.egg
Removing c:\users\hwy19\miniconda3\envs\opensim43\lib\site-packages\opensim-4.3-py3.7.egg
Copying opensim-4.3-py3.7.egg to c:\users\hwy19\miniconda3\envs\opensim43\lib\site-packages
opensim 4.3 is already the active version in easy-install.pth
Installing opensim-moco-generate-report-script.py script to C:\Users\hwy19\Miniconda3\envs\opensim43\Scripts
Installing opensim-moco-generate-report.exe script to C:\Users\hwy19\Miniconda3\envs\opensim43\Scripts

Installed c:\users\hwy19\miniconda3\envs\opensim43\lib\site-packages\opensim-4.3-py3.7.egg
Processing dependencies for opensim==4.3
Finished processing dependencies for opensim==4.3
(opensim43) PS C:\OpenSim 4.3\sdk\Python> python
Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import opensim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OpenSim 4.3\sdk\Python\opensim\__init__.py", line 6, in <module>
    from .simbody import *
  File "C:\OpenSim 4.3\sdk\Python\opensim\simbody.py", line 13, in <module>
    from . import _simbody
ImportError: DLL load failed: The specified module could not be found.
>>>
```

**Comment by aymanhab** [comment]
I think this is due to trying to use python 3.7 while the distribution was made against python 3.8. Can you switch the python version used by Blender to 3.8? Or you can compile from source using your specific python version instead. You can check/find the dependencies of the dlls to check if that's the case.

**Comment by hwy1992129** [comment]
Thanks, I will go check it...

**Comment by nishbo** [comment]
I encountered the same error. OpenSim 4.3 api doesn't install correctly on Python 3.7. After changing to Python 3.8, it works fine.
