### ISSUE TITLE
Bhargava2004SmoothedMuscleMetabolics has muscle_metabolic_rate declared as list output, but this output has no channels

### ISSUE THREAD

**Issue by Aravind-Sundararajan** [opensim-org/opensim-core#3136]
I believe the channel names should be the absolute path string for a muscle, as you can call
`met.getMuscleMetabolicRate(state,model.getMuscles.get(0).getAbsolutePathString());`
during a post hoc simulation to extract the individual muscle metabolic rate. 

Yet, calling
`
ao    = met.getOutput('muscle_metabolic_rate');
ao.getChannel(model.getMuscles.get(0).getAbsolutePathString());
`

`
java.lang.RuntimeException: Output 'muscle_metabolic_rate' does not have a channel named '/forceset/addbrev_r'.
	Thrown at ComponentOutput.h:260 in getChannel().

	at org.opensim.modeling.opensimCommonJNI.AbstractOutput_getChannel(Native Method)

	at org.opensim.modeling.AbstractOutput.getChannel(AbstractOutput.java:116)

`
I think channel names for list outputs have to be published in extendFinalizeFromProperties, as I wrote a simple mex to iterate through the ChannelMap and print channel names, and the map has size 0.

**Comment by nickbianco** [comment]
Hi @Aravind-Sundararajan, is there a specific reason why you need access to the Output channels directly? Is the `getMuscleMetabolicRate` accessor not sufficient for some reason?

**Comment by Aravind-Sundararajan** [comment]
Hi @nickbianco, for my use at the moment `getMuscleMetabolicRate` is sufficient, though my total met CoT I calculate in a post hoc doesn't match up with Moco's reported metabolic cost of transport when added as an OutputGoal even with weight 1.0, but that's neither here nor there. 

Ideally I would just add these outputs of the metabolics component to the list of outputs in analyzeMocoTrajectory or set up an AnalyzeTool with OutputReporter, but you can't here.

I presume someone may want to add all the muscles to the SmoothedMuscleMetabolics component and construct a custom goal like you minimize the sum of extensors or flexors across a joint with different weights, or maybe you want to add some set of MocoOutputGoal to minimize metabolic cost of transport of some subset of the muscles in the model. Though I know you can just add multiple of the SmoothedMuscleMetabolics component, and in the custom goal you can just call `getMuscleMetabolicRate` so it's maybe a moot point.

It may be nice in the future to have some function for Outputs that you can call like `getChannelNames()` that returns the keys of the ChannelMap and being able to cast `AbstractChannel` so you can get the value of channels, but you may not want to expose those things to matlab/python users. 

I envision something like:
```
for i = 0:component.getOutputNames().size()-1
    output    = OutputDouble.safeDownCast(component.getOutput(component.getOutputNames().get(i)));
    channel_names = output.getChannelNames();
    for j = 0:channel_names.size()-1
        channel = ChannelDouble.safeDownCast(output.getChannel(channel_names.get(j))); %AbstractChannel to Output<double>::Channel
        OutputData.(string(channel_names.get(j))) = channel.getValue(state);
    end
end
```

-Sunny

**Comment by nickbianco** [comment]
Having custom weights for each metabolic metabolic value would be a nice feature. The could potentially be achieved with some modifications to MocoOutputGoal, since we currently don't support list Outputs in that goal. Either way, it would be ideal to avoid adding an individual metabolics component for each muscle. Similarly, it would be nice to support list Outputs in the `analyze` functions, but I'm not sure when we'll get around to that.

What would the use case be for the sample code you've included? I still don't see how this is significantly different from the current `getMuscleMetabolicRate` interface.

**Comment by Aravind-Sundararajan** [comment]
Hi,

yes, in this use case it is practically equivalent, but maybe a user might want to do something like iterate over every component of a model and dump all outputs over each state in the states trajectory without just constructing an analyze tool. Though also matlab/python users can't iterate over ComponentsList of a model as far as I know either.
