### ISSUE TITLE
No module named 'opensim._simbody'

### ISSUE THREAD

**Issue by Mercury629** [opensim-org/opensim-core#3149]
Hello everyone, I am new to OpenSim and I have recently developed a small program based on opensim using Python. Everything works fine when I run it in pycharm, but when I use pyinstller to package it as an exe, it will report an error when I run it again. The information in cmd is as follows:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import inputmodel.DialogInput
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "inputmodel\DialogInput.py", line 6, in <module>
    import opensim
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "opensim\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "opensim\simbody.py", line 18, in <module>
  File "opensim\simbody.py", line 17, in swig_import_helper
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'opensim._simbody'
[3848] Failed to execute script main

Any idea how to fix this problem?

kind regards.

**Comment by aymanhab** [comment]
@Mercury629 Not sure what's specific about your environment but we're unlikely to support custom environments considering the variety of options and platforms that users have. Historically this had to do with PATH,  dynamic loading PATH or PYTHONPATH settings. With no more details I'll close this issue but please feel free to reopen if there're more helpful details that we can reproduce it. Thank you
