### ISSUE TITLE
finalizeConnection() failing when external force is added to model

### ISSUE THREAD

**Issue by itbellix** [opensim-org/opensim-core#3204]
Hi,
I am working with the OpenSim API in Matlab R2021b (on a Windows 10 machine) and I am trying to integrate an external force directly into my model - `arm26.osim`. At first, I tried to use the `ExternalLoads` class as in [this comment](https://github.com/opensim-org/opensim-core/issues/2324#issuecomment-433148482) but it did not really work (I had the feeling that the external load, that I was using just as a sort of wrapper for the external force to be applied) was kind of corrupting the data source for the force values. So I switched to directly applying an `ExternalForce` to my model, as in the following code snippet:

```matlab
% external_force variable is created above, together with external_force.mot 
% storing the time history of the force and the application point

model.addForce(external_force);
model.finalizeConnections();
``` 

When running this, I get alternatively one of the following errors:
```
Java exception occurred:
java.lang.RuntimeException: bad allocation

	at org.opensim.modeling.opensimSimulationJNI.Model_finalizeConnections__SWIG_0(Native Method)

	at org.opensim.modeling.Model.finalizeConnections(Model.java:830)
```
or
```
Java exception occurred:
java.lang.RuntimeException: ExternalForce: Data source external_force specified by name, but was set.

	at org.opensim.modeling.opensimSimulationJNI.Model_finalizeConnections__SWIG_0(Native Method)

	at org.opensim.modeling.Model.finalizeConnections(Model.java:830)
```

To solve this, I needed to modify my code: basically, after adding the force to the model, I set again its data source, and the errors disappear:
```matlab
% external_force variable is created above, together with external_force.mot 
% storing the time history of the force and the application point
model.addForce(external_force);

external_force_storage = Storage('external_force.mot', false);       % loading the external force data in a storage object
force_in_model = model.getForceSet().get(6);                               % getting the force from the model (6 is the right index)
ExternalForce.safeDownCast(force_in_model).setDataSource(external_force_storage);   % resetting the data source to be the one I expect

model.finalizeConnections();
```

I would think that somehow the information (pointers?) regarding which data source to use gets lost when the force is loaded into the model...

Does this appear plausible?

**Comment by aymanhab** [comment]
This seems plausible, while possibly a bug. Generally there're two mechanisms for populating the model tree of components:
1. XML: in which case all connections are based on names/paths that are serialized.
2. Creating the objects programmatically and carefully construct the tree to make sure connections are not lost along the way.
3. You're trying to mix and match by loading the model then adding a Force to it. In theory it should work but it appears there's unintneded interaction between 1&2 that would be good to sort out. If you can attach the full set of files and script needed to reproduce it would be great. Thank you

**Comment by itbellix** [comment]
Dear @aymanhab, thank you very much for your answer.
Indeed, I am using case 3, but today I was trying to reproduce the issue and it did not pop up.
I am not sure if that could be caused just by the fact that I restarted Matlab (and my laptopt as well) and somehow the issue was given by a not-really-clean workspace yesterday. In case the issue arises again, I will attach here what is needed to reproduce it. Thank you!

**Comment by itbellix** [comment]
Dear @fcanderson and @aymanhab, thank you for your answers.
I think it is indeed a memory management problem, since I am creating the `ExternalForce` in a separate function (hence, a different workspace), and then trying to use it in my main workspace.
I think that the implementation of how the `Storage` object is dealt with (in [ExternalForce.h(line 250)](https://github.com/opensim-org/opensim-core/blob/a01cf545485e8bc1f6e50b29ddeab229677de2c5/OpenSim/Simulation/Model/ExternalForce.h#L250) could be the cause of it, since once the `ExternalForce` object is returned by a function it kind of looses the connection with its storage (and that's why if I reset such a connection it works).

To conclude, I was using the API incorrectly, however I do think that updating the documentation (by mentioning maybe this problem) could help other users to avoid running into the same error.

**Comment by mrrezaie** [comment]
Hi,
I'm using Python and have similar issue. I'm trying to add external loads (GRF) to the model (`model.getForceSet().cloneAndAppend`), followed by further API usage in which `model.initSystem()` should be re-called. This is what happens:
1. If I write all codes consecutively, it works well.
2. If I put the externalForce sections into a function in either the same file or a separate file and call it, this error would be raised:

`  File F:\Python311\Lib\site-packages\opensim\simulation.py:27206 in initSystem`
`    return _simulation.Model_initSystem(self)`
`RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': ExternalForce: Data source subject11_trial03_grf specified by name, but  was set.`

Please notice the empty name (double space) after "but". It seems that the model no longer has access to the data source Storage.

OpenSim v.4.5

Thank you.
