### ISSUE TITLE
Python - Error initialising InverseKinematicsSolver - Wrong number or type of arguments

### ISSUE THREAD

**Issue by Arthur-Matta** [opensim-org/opensim-core#3292]
Hi there,

I'm trying to create a pipeline in which I read real-time quaternion data from 6 IMU sensors, update the model for every reading, and get the value of some coordinates at every step. I'm trying to avoid writing data to a file to read it afterwards and therefore managed to convert my data array directly into a TimeSeriesTable<Quaternion>.

For the sake of experimenting, I sampled the data from 2 IMU sensors. Following and adapting both implementations from [OpenSim IMUInverseKinematicsTool.cpp](https://github.com/opensim-org/opensim-core/blob/master/OpenSim/Tools/IMUInverseKinematicsTool.cpp#L165) and [OpenSenseRT](https://github.com/pslade2/RealTimeKin/blob/main/ik_streaming.py#L105) I first converted my data into a TimeSeriesTableQuaternion (as opposed to reading it form a .sto file) and then tried to initialise the InverseKinematicsSolver, as demonstrated bellow:

```python
import numpy as np
import opensim as osim

class DataLabels:
    THORAX = "thorax_imu"
    HUMERUS = "humerus_imu"

    @classmethod
    def to_list(cls):
        return [cls.THORAX, cls.HUMERUS]


SAMPLE_DATA = np.array(
    [
        [0, 0.9995429673603463, -0.008673246070566128, 0.02895804025163351, -0.0002512127741937707, 0.9988056889348111, 0.009225910844409206, 0.04797793296728128, 0.0004430222738762587],
        [0.01, 0.9983235155232013, -0.01648178176931649, 0.0554767580235808, -0.0009157195522055893, 0.9953451329047127, 0.01842024119373089, 0.0945817043153574, 0.001749950304193833],
        [0.02, 0.996553572768251, -0.02364517310391066, 0.0794879005037651, -0.001885753224544679, 0.9898697043858768, 0.0275592750627042, 0.1392244052239398, 0.003875524103277203],
        [0.03, 0.9944026364977537, -0.03036249384785823, 0.1011532414540192, -0.003088241732745588, 0.9826840433510849, 0.0366053997686734, 0.1815114641069645, 0.006760476956889426],
        [0.04, 0.9920155995198686, -0.03624118422120523, 0.1207152892736455, -0.004409740475433332, 0.974111394130037, 0.04551417126443761, 0.22119823325065, 0.01033410116740631],
        [0.05, 0.9894759113314432, -0.04174418491853947, 0.1384223432967164, -0.005839417483162094, 0.9644686836064071, 0.05440249635598614, 0.2581251100202142, 0.01455865068655974],
        [0.06, 0.9868508854848144, -0.04693285443957362, 0.154494844744801, -0.007347104141869534, 0.9540736552868223, 0.06326532185989953, 0.2921740174350191, 0.01937273531245459],
        [0.07, 0.9842021159098119, -0.05180189751605759, 0.1690667958671119, -0.00889814517826073, 0.943280037377913, 0.0721245581574768, 0.3231261113774534, 0.0247049659177489],
        [0.08, 0.9816277378550423, -0.05621921067018604, 0.1820376363912426, -0.01042514087690647, 0.9322749346658372, 0.08098224817958229, 0.3512470753675765, 0.03050923990061744],
        [0.09, 0.9791306321049124, -0.06029023660482678, 0.1937163440868847, -0.01192772725965339, 0.9212212941768754, 0.09000505440402377, 0.3766909623592524, 0.03680130722775423],
        [0.10, 0.9767195496681569, -0.06392963022845036, 0.2043356497812238, -0.01337407579504081, 0.9103290086705185, 0.09894767715988709, 0.399530682092155, 0.04342450028027244]
    ]
)

if __name__ == '__main__':
    # Load model
    model = osim.Model("../data/opensim/calibrated_ScapulothorachicJoint_Shoulder.osim")

    # Split data
    time = SAMPLE_DATA[:, 0]
    thorax_data = SAMPLE_DATA[:, 1:5]
    humerus_data = SAMPLE_DATA[:, 5:]

    # Convert data to Matrix<Quaternion>
    matrix = osim.MatrixQuaternion(len(SAMPLE_DATA), 2)
    for i, (t, h) in enumerate(zip(thorax_data, humerus_data)):
        matrix.set(i, 0, osim.Quaternion(*t))
        matrix.set(i, 1, osim.Quaternion(*h))

    # Construct TimeSeriesTable<Quaternion>
    quatTable = osim.TimeSeriesTableQuaternion(time, matrix, DataLabels.to_list())

    # Initialise ikSolver
    orientationsData = osim.OpenSenseUtilities().convertQuaternionsToRotations(quatTable)
    oRefs = osim.OrientationsReference(orientationsData)
    mRefs = osim.MarkersReference()
    coordinateReferences = osim.SimTKArrayCoordinateReference()

    state = model.initSystem()

    ikSolver = osim.InverseKinematicsSolver(model, mRefs, oRefs, coordinateReferences)
```

However, whatever I pass to ikSolver I always get the error bellow

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 3, in <module>
  File "/Users/arthurmatta/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.6008.17/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Users/arthurmatta/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/221.6008.17/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/arthurmatta/Documents/GitHub/EPMQ/STVgoDigital/src/myopensim.py", line 95, in <module>
    ikSolver = osim.InverseKinematicsSolver(model, mRefs, oRefs, coordinateReferences)
  File "/Applications/OpenSim 4.3/OpenSim 4.3.app/Contents/Resources/opensim/sdk/Python/opensim/simulation.py", line 34207, in __init__
    _simulation.InverseKinematicsSolver_swiginit(self, _simulation.new_InverseKinematicsSolver(*args))
TypeError: Wrong number or type of arguments for overloaded function 'new_InverseKinematicsSolver'.
  Possible C/C++ prototypes are:
    OpenSim::InverseKinematicsSolver::InverseKinematicsSolver(OpenSim::Model const &,std::shared_ptr< OpenSim::MarkersReference >,SimTK::Array_< OpenSim::CoordinateReference,unsigned int > &,double)
    OpenSim::InverseKinematicsSolver::InverseKinematicsSolver(OpenSim::Model const &,std::shared_ptr< OpenSim::MarkersReference >,SimTK::Array_< OpenSim::CoordinateReference,unsigned int > &)
    OpenSim::InverseKinematicsSolver::InverseKinematicsSolver(OpenSim::Model const &,std::shared_ptr< OpenSim::MarkersReference >,std::shared_ptr< OpenSim::OrientationsReference >,SimTK::Array_< OpenSim::CoordinateReference,unsigned int > &,double)
    OpenSim::InverseKinematicsSolver::InverseKinematicsSolver(OpenSim::Model const &,std::shared_ptr< OpenSim::MarkersReference >,std::shared_ptr< OpenSim::OrientationsReference >,SimTK::Array_< OpenSim::CoordinateReference,unsigned int > &)
```

Already tried replacing `mRefs` by `None`, removing `oRefs`, adding a value for `constraintWeight` but all to no avail.
I also checked the type of the variables I'm passing to ikSolver:

```
model = <opensim.simulation.Model; proxy of <Swig Object of type 'OpenSim::Model::Self *' at ########> >
mRefs = <opensim.simulation.MarkersReference; proxy of <Swig Object of type 'OpenSim::MarkersReference *' at ########> >
oRefs = <opensim.simulation.OrientationsReference; proxy of <Swig Object of type 'OpenSim::OrientationsReference *' at ########> >
coordinateReferences = <opensim.simulation.SimTKArrayCoordinateReference; proxy of <Swig Object of type 'SimTK::Array_< OpenSim::CoordinateReference > *' at ########> >
```

The only difference I noticed it the `mRefs` being `OpenSim::MarkersReference *` instead of `std::shared_ptr< OpenSim::MarkersReference >` and `coordinareReferences` missing the `,unsigned int>` at the end. I tried looking at OpenSim swig but found no bidding for `std::shared_ptr< OpenSim::MarkersReference >` nor a way to specify index type for `SimTK::Array_< OpenSim::CoordinateReference,unsigned int > `.

I'd very much appreciate some help to understand what I'm doing wrong and tips on how to procede moving forward.
For reference, I'm running OpenSim 4.3 on macOS Monterey (v12.5.1). I also append here the model I'm using as .txt since GH don't allow me to append a .osim file.

[ScapulothoracicJoint_Shoulder.osim.txt](https://github.com/opensim-org/opensim-core/files/9537774/ScapulothoracicJoint_Shoulder.osim.txt)

I searched the issues section and found no solution to my problem. If this is a duplicated issue, please link me the original issue.

**Comment by tkuchida** [comment]
My team encountered the same issue with `InverseKinematicsSolver` in Python (the original Issue was #3087; fixes in PRs #3089 and #3193). This was fixed in OpenSim 4.4, so you may just need to upgrade from 4.3. Note that, as of 4.4, you should just need to run 1 line in conda to upgrade: https://simtk-confluence.stanford.edu:8443/display/OpenSim/Conda+Package

**Comment by Arthur-Matta** [comment]
Thank you for your support @tkuchida! I'm going to upgrade my OpenSim and see what happens.
I'm closing this issue for now while attempting the proposed solution.

**Comment by d3721s** [comment]
May I ask, is real-time OpenSim based on IMU restricted to Python only? I don’t seem to find a C++ API.
