### ISSUE TITLE
Run time error when trying to visualize the sim

### ISSUE THREAD

**Issue by A-Artemis** [opensim-org/opensim-core#3344]
Ubuntu 22.04, Python 3.9.15, and opensim 4.4.

I am getting the following errors when I set the visualize=True, it runs when I set the visualize=False.
- `RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': SimTK Exception thrown at VisualizerProtocol.cpp:162:`
  - /home/aurelien/anaconda3/envs/opensim/simbody/libexec/simbody/Final system error was errno=2 (No such file or directory).
  (Required condition 'status == 0' was not met.)
- `RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': std::exception` 

These are the steps I took to create my conda environment

1. conda create -n opensim python=3.9
2. conda activate opensim
3. conda install -c opensim-org opensim=4.4=py39np120

Am I missing an install step to be able to visualize the sim?

**Comment by aymanhab** [comment]
@AlbertoCasasOrtiz not familiar with how/if visualizer works in Conda environment, worth documentation at the least and/or fixing if possible.

**Comment by AlbertoCasasOrtiz** [comment]
@aymanhab I have tested the 2nd colab tutorial setting visualizer to true with `model.setUseVisualizer(True)` and it is not working for me. When it comes to init the system (`state = model.initSystem()`), it hangs forever. If you restart the runtime, it shows the following error:

```
<ipython-input-11-bed98f94f295> in <module>
      1 # Initialize model.
----> 2 state = arm.initSystem()
      3 

/usr/local/lib/python3.8/site-packages/opensim/simulation.py in initSystem(self)
  25869         """
> 25870         return _simulation.Model_initSystem(self)
  25871 

RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': SimTK Exception thrown at VisualizerProtocol.cpp:177:
  Error detected by Simbody method VisualizerProtocol: An attempt to read() 1 bytes from pipe 46 failed with errno=4 (Interrupted system call).
  (Required condition 'retval!=-1' was not met.)
```

**Comment by mrrezaie** [comment]
Hi, I'm using OpenSim moco (4.4.1) conda package (py311) and when running any of these codes, the console crashes and terminates.
```python
model = osim.Model('Rajagopal2015.osim')
model.setUseVisualizer(True)
model.initSystem()
```
```python
model = osim.Model('Rajagopal2015.osim')
viz = osim.VisualizerUtilities()
viz.showModel(model)
```
It's not model specific and setting geometry directory has no effect either (`osim.ModelVisualizer.addDirToGeometrySearchPaths('./geometry')`).

**Comment by mrrezaie** [comment]
> do you think your bug is related to the current issue?

@nickbianco , YES, this is exactly the same as what @AlbertoCasasOrtiz had reported earlier in this issue.

> If you're able to, can you try to reproduce the bug on [the 4.4.1 release](https://github.com/opensim-org/opensim-core/releases/tag/4.4.1) using the normal install approach for scripting?

I'm going to test it. Which Python version it has been built for?

**Comment by nickbianco** [comment]
Apologies, @mrrezaie, I didn't read the previous comments carefully. It looks like the release was build with Python 3.8. Thank you for testing!

**Comment by mrrezaie** [comment]
Hi, I tested the [the 4.4.1 release](https://github.com/opensim-org/opensim-core/releases/tag/4.4.1). After installation, when I called `import opensim`, I got `DLL load failed` error. I could fix it by manually adjusting the OpenSim bin path, `F:\opensim-core-4.4.1-win\bin` instead of the following line. Now, it works. It requires the correct path, the `curFolder` variable in this line refers to the Python installation directory not OpenSim. 
https://github.com/opensim-org/opensim-core/blob/81c2455e13f953b4d83bc988107b60ebc3071889/Bindings/Python/__init__.py#L7

Regarding the visualizer, it still doesn't work. Please see this:

https://github.com/opensim-org/opensim-core/assets/38867713/d50b832a-0ef9-4eb5-9356-731bc640bf2a

Have I forgotten something?

**Comment by nickbianco** [comment]
Hi @mrrezaie, thanks again for testing. It seems like the `__init__.py` script isn't working as intended. Could you try something that worked for me locally? Add the following code to the top of your script (and replace `<dir/to/bin>` with the `bin` folder directory for your local install):

```
import os
os.add_dll_directory('<dir/to/bin>')
```

**Comment by mrrezaie** [comment]
> Add the following code to the top of your script (and replace <dir/to/bin> with the bin folder directory for your local install):
> ```
> import os
> os.add_dll_directory('<dir/to/bin>')
> ```

@nickbianco, it didn't help. 

But I think I found the issue. To invoke `simbody-visualizer.exe` programmatically, the `opensim-core-4.4.1-win\bin\` directory must exist in the system (or user) environment path. `os.add_dll_directory('<dir/to/bin>')` cannot handle this. I used `os.environ["PATH"] += os.pathsep+'<dir/to/bin>'` instead. 

There is a strange behavior when the drives of **Python working directory** and **OpenSim installation directory** are not identical, i.e., I had put the OpenSim 4.4.1 bin folder in `F:\` drive, whereas my Python working directory and the model file were in `C:\` drive. In this case, it doesn't work (please see the video I posted earlier). Could you reproduce this?

> Could you try something that worked for me locally?

Did you have same drives for both directories as I just explained? If the drives are identical, it works very well for me. This happens for the Conda package as well.

I also found a temporary fix for the installation issue. This code can be added at the beginning of the `setup.py` file (e.g., before line 6) to update the `__init__.py` file before installation (adopted from the `setup_win_python38.py` file in OpenSim 4.4.0, I just merged them):
```python
import fileinput

install_path = os.path.abspath('../../bin').replace(os.sep, '/')
print ('install path found as '+ install_path)
with fileinput.FileInput('opensim/__init__.py', inplace=True, backup='.bak') as file:
    for line in file:
        print(line.replace('DLL_PATH', "'" + install_path + "'"), end='')
```
And this code can be added instead of the following lines in the `__init__.py` file:
https://github.com/opensim-org/opensim-core/blob/81c2455e13f953b4d83bc988107b60ebc3071889/Bindings/Python/__init__.py#L7-L9
```python
os.add_dll_directory(DLL_PATH)
os.environ["PATH"] += os.pathsep + DLL_PATH
```
(the last one is an alternative to adding the OpenSim bin directory the environment path manually). If this looks good to you, I can open a pull request for it.

Hope this helps,
Mohammadreza

**Comment by A-Artemis** [comment]
This is the only solution that I have found that allows me to use the visualizer for 4.4 (On Ubuntu 22 and Python 3.11).

1. Follow the instructions here https://github.com/opensim-org/opensim-core/wiki/Build-Instructions
2. Place these two line lines at the bottom of your `~/.bashrc`
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/opensim-workspace/opensim-core-dependencies-install/simbody/lib
export PYTHONPATH=~opensim-core/sdk/Python:$PYTHONPATH
```
3. Activate (or create) your conda environment
```
# You might need to run the following line
# apt-get install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6

conda create -n opensim -c conda-forge anaconda python==3.11.4
conda activate opensim
conda install -c anaconda libgcc
```

4. Go to  ```cd ~/opensim-core/sdk/Python``` and check that `setup.py` and `opensim` are present.
5. Run `pip install -e .`

It should now be possible to run with the visualizer!

**Comment by nickbianco** [comment]
@mrrezaie 

> Did you have a same drive for the both directories as I just explained? If the drives letters are identical, it works very well for me.

Ah, that makes sense. I would probably recommend that, in general, to keep things related to your OpenSim install on the same drive. But if these changes fix that, great! 

> If this looks good to you, I can open a pull request for it.

Sure, that would be great! I'd be happy to test your changes once the PR is up.

**Comment by nickbianco** [comment]
@A-Artemis, is the line `export PYTHONPATH=~opensim-core/sdk/Python:$PYTHONPATH` needed just for the visualizer or for any Python usage on Linux?

**Comment by A-Artemis** [comment]
@nickbianco No, it is not needed for the visualizer. But I do use it so that I can debug though PyCharm.

**Comment by nickbianco** [comment]
@A-Artemis, sounds good. We can update the Linux build documentation and test the changes against the Google Colab tutorial scripts we have. @AlbertoCasasOrtiz, what do you think?

**Comment by AlbertoCasasOrtiz** [comment]
@A-Artemis, @mrrezaie Thank you for looking into this!. I will test against the google colab tutorials and get back to you with the results.

**Comment by AlbertoCasasOrtiz** [comment]
A little update to this issue @aymanhab @nickbianco :

- The conda package does not contain the simbody visualizer, this is why if you install using `conda install -c opensim-org opensim`, and activate visualization, it crashes. I was able to get a complete error message in Ubuntu 22.04. Is esentially the same error we where getting initially, but now it shows that the executable 'simbody-visualizer' cannot be found.

```
Traceback (most recent call last):
  File "/home/albert/test.py", line 115, in <module>
    state = arm.initSystem()
            ^^^^^^^^^^^^^^^^
  File "/home/albert/anaconda3/envs/test/lib/python3.11/site-packages/opensim/simulation.py", line 24815, in initSystem
    return _simulation.Model_initSystem(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': SimTK Exception thrown at VisualizerProtocol.cpp:165:
  Error detected by Simbody method VisualizerProtocol::ctor(): Unable to spawn executable 'simbody-visualizer' from directories:
  /home/albert/anaconda3/envs/test/bin/
  /home/albert/anaconda3/envs/test/bin/
  /home/albert/anaconda3/condabin/
  /home/albert/anaconda3/bin/
  /usr/local/sbin/
  /usr/local/bin/
  /usr/sbin/
  /usr/bin/
  /sbin/
  /bin/
  /usr/games/
  /usr/local/games/
  /snap/bin/
  Final system error was errno=2 (No such file or directory).
  (Required condition 'status == 0' was not met.)

Traceback (most recent call last):
  File "/home/albert/test.py", line 115, in <module>
    state = arm.initSystem()
            ^^^^^^^^^^^^^^^^
  File "/home/albert/anaconda3/envs/test/lib/python3.11/site-packages/opensim/simulation.py", line 24815, in initSystem
    return _simulation.Model_initSystem(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': std::exception
```

 - I have checked the conda package from https://anaconda.org/opensim-org/opensim, and the simbody-visualizer executable is not present. I think this is the reason why @A-Artemis could not use it on Ubuntu 22.04, and why it is failing in the colab notebooks.
 
 - If I install opensim-core from scratch, and try to execute the visualizer on isolation, I get `RuntimeError: std::exception in 'SimTK::State & OpenSim::Model::initSystem()': std::exception`. After executing `/home/albert/opensim-core/sdk/Simbody/libexec/simbody/simbody-visualizer: error while loading shared libraries: libSimTKcommon.so.3.8: cannot open shared object file: No such file or directory` as @A-Artemis suggested, it can be executed on isolation.

- If I add the directory `/home/albert/opensim-core/sdk/Simbody/libexec/simbody/` to conda path with `conda develop`, the new path is shown in the error as a place where it looked for the executable, but it is still throwing the same error (even with the executable in one of the directories now). If I add it to PYTHONPATH, there is not difference either.

**Comment by A-Artemis** [comment]
I have been having issues making the opensim-core on various Ubuntus. If following the build instructions is not working then another way to get the visualisation to work in conda on Ubuntu is: 

1. conda install -c opensim-org opensim
2. conda install -c conda-forge simbody

This should allow you to enable visualisation.

**Comment by aymanhab** [comment]
Hi, I see you closed the issue, can you comment if there is a bug or documentation that was missing? Thanks

**Comment by A-Artemis** [comment]
> Hi, I see you closed the issue, can you comment if there is a bug or documentation that was missing? Thanks

Hi, I would say that the documentation could be updated.
The first page I went to was https://github.com/opensim-org/opensim-core?tab=readme-ov-file  Then I wanted to first install OpenSim for conda with https://anaconda.org/opensim-org/opensim but this did not work for visualization. I followed the docs on https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+Python and got some success (see comments above) but this was not ideal for my workflow.

In Python, you make a OpenSim model with:
```python
# Create the model
self.model = Model(path_to_model)
self.model.setUseVisualizer(visualize=True) 
```

and I thought that using the visualizer would be a rather common practice so I wasn't understanding why my install was working well for OpenSim except the visualization.

Then I read up some more and found https://github.com/simbody/simbody and its conda package https://anaconda.org/conda-forge/simbody. This solution now works the best for me and I think it would be simple for everyone else.

Overall, it was not clear to me at the time that the limitation of installing only opensim-core had on visualization. To me the GUI was https://simtk.org/frs/?group_id=91 which I did not need the full features of. I just wanted the little box that pops up with the orange floor to see the models motion.

I suggest the following:

1. Update the docs. For [1](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Conda+Package) in the Troubleshooting section, mention that: "If you are getting an error with enabling the visualizer, we recommend installing these packages ... ". And for [2](https://simtk-confluence.stanford.edu:8443/display/OpenSim/Scripting+in+Python), edit the banner to "... unrelated to the OpenSim application/GUI. If you require those features alongside this conda install, we recommend you to ..."
2. If the user calls `self.model.setUseVisualizer(visualize=True)`  and Simbody is not installed, then update the RuntimeError message to mention that the user could be missing the Simbody package.
3. Add the required Simbody code to https://anaconda.org/opensim-org/opensim so that the visualiser can be enabled out the box.

I can understand if 2 and 3 are not feasible, but updating the documentation would be nice 👍
