### ISSUE TITLE
Error while importing opensim library in Python 3.9/3.10

### ISSUE THREAD

**Issue by Aleph-Zero0** [opensim-org/opensim-core#3425]
Hello, I am using OpenSim 4.4 and Python 3.9(no conda) on Windows 10.
I just want to run a CMC simulation with script but when I try to import opensim I get

```
Traceback (most recent call last):
File "<script_dir>\CMC_Run.py", line 3, in <module>
    import opensim as osim
File "C:\OpenSim 4.4\sdk\Python\opensim\__init__.py", line 9, in <module>
    from .simbody import *
File "C:\OpenSim 4.4\sdk\Python\opensim\simbody.py", line 13, in <module>
    from . import _simbody
ImportError: DLL load failed while importing _simbody: The specified module could not be found.
```

What should I do?

**Comment by Aleph-Zero0** [comment]
Switching to Python 3.8 solved the problem
