### ISSUE TITLE
Xml::WriteToFile() failed

### ISSUE THREAD

**Issue by Trash-J** [opensim-org/opensim-core#3427]
I get the following error when trying to run a program that uses OpenSim:

```Traceback (most recent call last):
  File "C:\Robotics\Q3\Deep Learning\Project\Direct3DKinematicEstimation\ms_model_estimation\opensim_utils\OpenSimModel.py", line 444, in scaling
    success = scaleTool.run()
  File "C:\OpenSim4.4\sdk\Python\opensim\tools.py", line 2246, in run
    return _tools.ScaleTool_run(self)
RuntimeError: std::exception in 'bool OpenSim::ScaleTool::run() const': SimTK Exception thrown at Xml.cpp:115:
  Error detected by Simbody method Xml::writeToFile(): Failed to write to the Xml file 'resources/opensim/BMLmovi/BMLmovi/Subject_11_F_MoSh/scale.osim' with error ' (line=1, col=1)'.
  (Required condition 'saveOK' was not met.)
```

What could be the cause of this error and how can I fix it? The file it mentions looks normal. The code is from the `generate_opensim_gt.py` module from this repository: https://github.com/bittnerma/Direct3DKinematicEstimation.

**Comment by Trash-J** [comment]
Ok I will do that, wasn't aware of the forum. Thank you!
