### ISSUE TITLE
Fix `CMC_TaskSet` memory leaks whenever it is copied

### ISSUE THREAD

**Issue by adamkewley** [opensim-org/opensim-core#3457]
Downstream issue: https://github.com/ComputationalBiomechanicsLab/opensim-creator/issues/432

`CMC_TaskSet` leaks memory whenever it is copied.

Repro (Linux):

- Build opensim and its dependencies with address sanitizer:

```bash
CXXFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" cmake -S dependencies/ -B ../osim-deps-build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=${PWD}/../osim-deps-install -DOPENSIM_WITH_CASADI=NO -DOPENSIM_WITH_TROPTER=NO

cmake --build ../osim-deps-build/ -j16 -v

CXXFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address" cmake -S . -B ../osim-build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=${PWD}/../osim-install -DOPENSIM_WITH_CASADI=NO -DOPENSIM_WITH_TROPTER=NO -DOPENSIM_DEPENDENCIES_PATH=${PWD}/../osim-deps-install

cmake --build ../osim-build/ -j16 -v
```

- Strip out `opensim-cmd` and replace it with an empty `main` (this is so that we have _something_ to run):

```c++
#include <OpenSim/Tools/CMC_TaskSet.h>

int main(int, char**)
{
}
```

- Rebuild and rerun with appropriate `ASAN_OPTIONS`:

```bash
export ASAN_OPTIONS="malloc_context_size=30"
cmake --build ../osim-build/ -j16 --target opensim-cmd && ../osim-build/opensim-cmd
```

- This produces a leak report that shows `CMC_TaskSet` leaks via OpenSim's static initialization (`Object::registerType`). Entire report here: https://gist.github.com/adamkewley/4854a3e289b3f869072339a5f3923df1 , leak example:

```text
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7fead49de337 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
    #1 0x7fead39fdc03 in OpenSim::ArrayPtrs<OpenSim::TrackingTask>::operator=(OpenSim::ArrayPtrs<OpenSim::TrackingTask> const&) /home/adam/opensim-core/OpenSim/Common/ArrayPtrs.h:210
    #2 0x7fead39fdc03 in OpenSim::PropertyObjArray<OpenSim::TrackingTask>::PropertyObjArray(OpenSim::PropertyObjArray<OpenSim::TrackingTask> const&) /home/adam/opensim-core/OpenSim/Common/PropertyObjArray.h:71
    #3 0x7fead39fdc03 in OpenSim::PropertyObjArray<OpenSim::TrackingTask>::clone() const /home/adam/opensim-core/OpenSim/Common/PropertyObjArray.h:76
    #4 0x7fead0c7444e in OpenSim::ArrayPtrs<OpenSim::Property_Deprecated>::operator=(OpenSim::ArrayPtrs<OpenSim::Property_Deprecated> const&) /home/adam/opensim-core/OpenSim/Common/ArrayPtrs.h:212
    #5 0x7fead0c7444e in OpenSim::PropertySet::operator=(OpenSim::PropertySet const&) /home/adam/opensim-core/OpenSim/Common/PropertySet.cpp:68
    #6 0x7fead3a14e97 in OpenSim::CMC_TaskSet::CMC_TaskSet(OpenSim::CMC_TaskSet const&) /home/adam/opensim-core/OpenSim/Tools/CMC_TaskSet.h:108
    #7 0x7fead3a15665 in OpenSim::CMC_TaskSet::clone() const /home/adam/opensim-core/OpenSim/Tools/CMC_TaskSet.h:47
    #8 0x7fead0bde631 in OpenSim::Object::registerType(OpenSim::Object const&) /home/adam/opensim-core/OpenSim/Common/Object.cpp:524
    #9 0x7fead3ca9b52 in RegisterTypes_osimTools /home/adam/opensim-core/OpenSim/Tools/RegisterTypes_osimTools.cpp:99
    #10 0x7fead38b8701 in __static_initialization_and_destruction_0 /home/adam/opensim-core/OpenSim/Tools/RegisterTypes_osimTools.cpp:65
    #11 0x7fead38b8701 in _GLOBAL__sub_I_RegisterTypes_osimTools.cpp /home/adam/opensim-core/OpenSim/Tools/RegisterTypes_osimTools.cpp:128
    #12 0x7fead532247d in call_init elf/dl-init.c:70
    #13 0x7fead5322567 in call_init elf/dl-init.c:33
    #14 0x7fead5322567 in _dl_init elf/dl-init.c:117
    #15 0x7fead533c2e9  (/lib64/ld-linux-x86-64.so.2+0x202e9)
```

- Replace `opensim-cmd` stub code with code that initializes `CMC_TaskSet` in a loop:

```c++
#include <OpenSim/Tools/CMC_TaskSet.h>

int main(int, char**)
{

        for (int i = 0; i < 100; ++i)
        {
                OpenSim::CMC_TaskSet s;
                // OpenSim::CMC_TaskSet copy{s};  // leak
        }
}
```

- Rebuild and rerun as above: **this does not increase the number of leaks**

- Modify `opensim-cmd` stub code with code that _copies_ the `CMC_TaskSet`:

```c++
#include <OpenSim/Tools/CMC_TaskSet.h>

int main(int, char**)
{

        for (int i = 0; i < 100; ++i)
        {
                OpenSim::CMC_TaskSet s;
                OpenSim::CMC_TaskSet copy{s};  // leak
        }
}
```

- The number of leaks has increased 

- Comparison of before and after adding the copy line:

```bash
# BEFORE
# cmake --build ../osim-build/ -j16 --target opensim-cmd && ../osim-build/opensim-cmd 2>&1 | grep "leak"

Direct leak of 128 byte(s) in 1 object(s) allocated from:
Direct leak of 128 byte(s) in 1 object(s) allocated from:
Direct leak of 128 byte(s) in 1 object(s) allocated from:
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
SUMMARY: AddressSanitizer: 400 byte(s) leaked in 5 allocation(s).

# AFTER
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 3200 byte(s) in 25 object(s) allocated from:
Direct leak of 128 byte(s) in 1 object(s) allocated from:
Direct leak of 128 byte(s) in 1 object(s) allocated from:
Direct leak of 128 byte(s) in 1 object(s) allocated from:
Indirect leak of 200 byte(s) in 25 object(s) allocated from:
Indirect leak of 200 byte(s) in 25 object(s) allocated from:
Indirect leak of 200 byte(s) in 25 object(s) allocated from:
Indirect leak of 200 byte(s) in 25 object(s) allocated from:
Indirect leak of 200 byte(s) in 25 object(s) allocated from:
Indirect leak of 200 byte(s) in 25 object(s) allocated from:
Indirect leak of 200 byte(s) in 25 object(s) allocated from:
Indirect leak of 200 byte(s) in 25 object(s) allocated from:
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
SUMMARY: AddressSanitizer: 40400 byte(s) leaked in 505 allocation(s).
```

**Comment by adamkewley** [comment]
Speculation about the bug is also in downstream:

- https://github.com/ComputationalBiomechanicsLab/opensim-creator/issues/379

And I should be able to PR a fix for it (I think)
