### ISSUE TITLE
DLL load failed while importing _simbody

### ISSUE THREAD

**Issue by hmejbri** [opensim-org/opensim-core#3780]
I get this error when running `& 'opensim-core-windows-build-script.ps1'` to build opensim on windows

ImportError: Failed to import test module: test_swig_additional_interface
Traceback (most recent call last):
  File "C:\Users\Houssem\AppData\Local\Programs\Python\Python39\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Houssem\AppData\Local\Programs\Python\Python39\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\opensim-core\sdk\python\opensim\tests\test_swig_additional_interface.py", line 9, in <module>
    import opensim as osim
  File "C:\opensim-core\sdk\python\opensim\__init__.py", line 18, in <module>
    from .simbody import *
  File "C:\opensim-core\sdk\python\opensim\simbody.py", line 10, in <module>
    from . import _simbody
ImportError: DLL load failed while importing _simbody: The specified module could not be found.

**Comment by AlbertoCasasOrtiz** [comment]
I think it should work. If I'm not wrong, the scripts install Python and numpy, but I recently discovered it has problems if multiple python versions are installed. I'm working on solving that.

**Comment by nickbianco** [comment]
@hmejbri do you have multiple Python versions installed? What Python enviroment manager are you using (if any)?

**Comment by aymanhab** [comment]
For the record, we're using python 3.10 on ci, in the unlikely case the problem is python version specific.

**Comment by nickbianco** [comment]
Closing due to inactivity.
