### ISSUE TITLE
Java bindings fails on Windows with Matlab 2024b after building from source

### ISSUE THREAD

**Issue by nickbianco** [opensim-org/opensim-core#3958]
Reported by Amir Esrafilian. After building OpenSim from source at `main` on Windows 11, installing the Java bindings (built using openjdk 23), and running `configureOpenSim.m`, trying to construct a model fails with the typical DLL load failure error:

```
Failed to load one or more dynamic libraries for OpenSim.
java.lang.UnsatisfiedLinkError: D:\Git_Win\EMG_COMAK\EMG-Assisted-COMAK-install\bin\osimJavaJNI.dll: A dynamic link library (DLL) initialization routine failed
Make sure OpenSim's bin directory is on your PATH.
See https://simtk-confluence.stanford.edu/display/OpenSim40/Scripting+with+Matlab
Java exception occurred:
java.lang.UnsatisfiedLinkError: org.opensim.modeling.opensimSimulationJNI.new_Model__SWIG_0()J
	at org.opensim.modeling.opensimSimulationJNI.new_Model__SWIG_0(Native Method)
	at org.opensim.modeling.Model.<init>(Model.java:840)
```

Currently investigating whether this is an issue with Matlab 2024b or something else.

**Comment by nickbianco** [comment]
Installing the OpenSim 4.5 distribution via `configureOpenSim.m` works successfully.

**Comment by aymanhab** [comment]
jdk version lust match whatever version used by matlab or they need to be compatible.

**Comment by aymanhab** [comment]
For the record, local build works out of the box without issue on R2022a update 8

**Comment by aymanhab** [comment]
Will try the artifact built on ci using coretto as java sdk here https://github.com/opensim-org/opensim-core/pull/3965

**Comment by nickbianco** [comment]
@aymanhab do you have any updates on this issue? I'm running into a similar issue with Jenny, she's trying to install a build artifact into Matlab on Windows.

**Comment by aymanhab** [comment]
@nickbianco My conjecture was that it has to do with the java jdk used on ci. Would it be possible to test the installation using the latest gui artifact?

**Comment by nickbianco** [comment]
We'll give that a try!

**Comment by sebastianskejoe** [comment]
Hi! I believe I'm running into the same problem with MATLAB R2024a. Is there any news regarding this issue?

**Comment by clnsmith** [comment]
I'm also having the same issue with MATLAB R2022a.

I used choco install jdk8 -y in powershell to update to the latest version (jdk1.8.0_211)

I tried configure and generate in cmake to make sure it was pointing to this java install ^

Used Visual Studio Community 2022 Version 17.13.6 to build and install

This did not fix the issue. Any ideas of what else to try?

**Comment by clnsmith** [comment]
https://www.mathworks.com/help/matlab/ref/matlab_jenv.html

I used matlab_jenv to force matlab to use jdk1.8.0_211/jre and verified inside matlab using version -java

This still did not fix the problem.

**Comment by clnsmith** [comment]
I did a clean install of MATLAB 2024b and now everything is working... no idea of the true underlying cause.

**Comment by nickbianco** [comment]
Thanks for the investigation @clnsmith. When you reinstalled Matlab, did it revert to an older jdk, or was it using `jdk1.8.0_211/jre`?

**Comment by clnsmith** [comment]
In newly installed MATLAB 2024b
>> version -java

ans =

    'Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'

Interestingly, this is not the version installed via choco and also doesn't seem to be located in this folder where several other versions of java are installed (C:\Program Files\Java)... so I think MATLAB must have its own version somewhere?

I have not rebuilt OpenSim with Visual Studio since installing this new version of MATLAB... so it is using OpenSim compiled against jdk1.8.0_211/jre installed via choco.

**Comment by nickbianco** [comment]
I would assume Matlab has it's own packaged Java version, but I've never verified myself. Thanks for the investigation regardless! Getting Matlab and our Java bindings in sync can be a pain.

**Comment by nickbianco** [comment]
> Note, 2025a did not show any java environment prior to me configuring it with the jenv command (i.e., no "factory" mode), perhaps MATLAB has stopped building this in?

It seems that, [starting with version 2025a, MATLAB is now using JavaScript and HTML for the desktop and graphics system rather than Java](https://blogs.mathworks.com/matlab/2025/05/16/whats-with-all-the-big-changes-in-r2025a/). This explains why your installed 2025a does not have a Java environment installed.

FYI @aymanhab
